[general]
background = "#002B36"
border = "#222C22"
horizontal_rule = "#1B1B1B"
scrollbar = "#1B1B1B"
unread_indicator = "#99FF66"
highlight_indicator = "#4A6B43"

[text]
primary = "#17D488"
secondary = "#99FF99"
tertiary = "#33FF77"
success = "#19C919"
error = "#FF5555"
warning = "#FFEB3B"
info = "#66FFB2"
debug = "#C0FCCC"
trace = "#B0EFC8"

[buffer]
action = "#00FF99"
background = "#002B36"
background_text_input = "#141914"
background_title_bar = "#002B36"
border = "#00140000"
border_selected = "#17D488"
code = "#16A085"
highlight = "#1FAB89"
nickname = "#ADFF2F"
selection = "#024902"
timestamp = "#6FCF97"
topic = "#17D488"
url = "#39FF14"
nickname_offline = "#555F55"

[buffer.server_messages]
default = "#C7F464"

[buttons.primary]
background = "#002B36"
background_hover = "#232323"
background_selected = "#0A170A"
background_selected_hover = "#1A3A1A"

[buttons.secondary]
background = "#222C22"
background_hover = "#295429"
background_selected = "#334D33"
background_selected_hover = "#467346"
